stages:
  prepare:
    cmd: python featurize.py data/prepared/ data/features/
    params:
      - featurize.degree
    deps:
      - featurize.py 
      - data/prepared/
    outs:
      - data/features